### ISSUE TITLE
showImagePicker da pagina de profile não existe mais nas versões atuais do pacote react-native-image-picker

### ISSUE THREAD

**Issue by Peroconino** [EliasGcf/gobarber-mobile#3]
Olá gostaria de avisar sobre um probleminha que eu tive quando eu estava fazendo o bootcamp e cheguei nessa parte. Durante a aula o Diego usou o metodo showImagePicker do pacote react-native-image-picker porém as versões mais atuais não existe mais esse método. Então só queria deixar avisado para gerações futuras do bootcamp pra caso se deparem com o mesmo problema ao inves de executar um simples **yarn add react-native-image-picker** para adicionar a ultima versão do pacote executar **yarn add react-native-image-picker@2.3.1**. 

Obrigado e até mais! :)

**Comment by EliasGcf** [comment]
Opa @LeandroFontellas, tudo bem?

Muito obrigado pelo feedback! Pode deixar que vamos estar atentos para futuros usos. ;)

Bons estudos 💜
